// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Flight struct {
	Name        string `json:"name"`
	Source      string `json:"source"`
	Destination string `json:"destination"`
}
