// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Name struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Train struct {
	Name string `json:"name"`
	Num  int    `json:"num"`
}
